name: engineer_app_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: 12.0.0
  cloud_firestore: ^4.13.1
  fl_chart: ^0.63.0
  cached_network_image: ^3.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
